<?php

/**
 * Implements hook_theme().
 */
function custom_pages_theme($existing, $type, $theme, $path) {
  return array(
    'about' => array(
        'variables' => array('test_var' => NULL),
    ),
    'research' => array(
        'variables' => array('test_var' => NULL),
    ),
    'services' => array(
        'variables' => array('test_var' => NULL),
    ),
    'outreach' => array(
        'variables' => array('test_var' => NULL),
    ),
    'news' => array(
        'variables' => array('test_var' => NULL),
    ),
    'cellularmolecularbiology' => array(
        'variables' => array('test_var' => NULL),
    ),
    'cellularmolecularmedicine' => array(
        'variables' => array('test_var' => NULL),
    ),
    'chemicalphysicalbiology' => array(
        'variables' => array('test_var' => NULL),
    ),
    'environmentalbiology' => array(
        'variables' => array('test_var' => NULL),
    ),
    'molmicroinfecbio' => array(
        'variables' => array('test_var' => NULL),
    ),
    'aspergillus' => array(
        'variables' => array('test_var' => NULL),
    ),
  );
}
