<?php

/**
 * Implements hook_theme().
 */
function custom_pages_theme($existing, $type, $theme, $path) {
  return array(
    'about' => array(
        'variables' => array('test_var' => NULL),
    ),
    'research' => array(
        'variables' => array('test_var' => NULL),
    ),
    'services' => array(
        'variables' => array('test_var' => NULL),
    ),
    'outreach' => array(
        'variables' => array('test_var' => NULL),
    ),
    'news' => array(
        'variables' => array('test_var' => NULL),
    ),
    'demo_bootstrap_tabs' => array(
      'variables' => array('view' => NULL, 'rows' => NULL),
      'path' => drupal_get_path('module', 'custom_pages') . '/templates',
    ),
  );
}
